version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hushh
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
